export const Barangays = [
  { value: "Arena Blanco", text: "Arena Blanco" },
  { value: "Ayala", text: "Ayala" },
  { value: "Baliwasan", text: "Baliwasan" },
  { value: "Baluno", text: "Baluno" },
  { value: "Barangay Zone I (Pob.)", text: "Barangay Zone I (Pob.)" },
  { value: "Barangay Zone II (Pob.)", text: "Barangay Zone II (Pob.))" },
  { value: "Barangay Zone III (Pob.)", text: "Barangay Zone III (Pob.))" },
  { value: "Barangay Zone IV (Pob.)", text: "Barangay Zone IV (Pob.)" },
  { value: "Boalan", text: "Boalan" },
  { value: "Bolong", text: "Bolong" },
  { value: "Buenavista", text: "Buenavista" },
  { value: "Bunguiao", text: "Bunguiao" },
  { value: "Busay (Sacol Island)", text: "Busay (Sacol Island)" },
  { value: "Cabaluay", text: "Cabaluay" },
  { value: "Cabatangan", text: "Cabatangan" },
  { value: "Cacao", text: "Cacao" },
  { value: "Calabasa", text: "Calabasa" },
  { value: "Camino Nuevo", text: "Camino Nuevo" },
  { value: "Campo Islam", text: "Campo Islam" },
  { value: "Canelar", text: "Canelar" },
  { value: "Capisan", text: "Capisan" },
  { value: "Cawit", text: "Cawit" },
  { value: "Culianan", text: "Culianan" },
  { value: "Dita", text: "Dita" },
  { value: "Divisoria", text: "Divisoria" },
  { value: "Dulian (Upper Bunguiao)", text: "Dulian (Upper Bunguiao)" },
  { value: "Dulian (Upper Pasonanca)", text: "Dulian (Upper Pasonanca)" },
  { value: "Guisao", text: "Guisao" },
  { value: "Guiwan", text: "Guiwan" },
  { value: "Kasanyangan", text: "Kasanyangan" },
  { value: "La Paz", text: "La Paz" },
  { value: "Lamisahan", text: "Lamisahan" },
  { value: "Landang Gua", text: "Landang Gua" },
  { value: "Landang Laum", text: "Landang Laum" },
  { value: "Lapakan", text: "Lapakan" },
  { value: "Latuan (Curuan)", text: "Latuan (Curuan)" },
  { value: "Licomo", text: "Licomo" },
  { value: "Limaong", text: "Limaong" },
  { value: "Limpapa", text: "Limpapa" },
];
