export const Barangays = [
  { value: "Arena Blanco", text: "Arena Blanco" },
  { value: "Ayala", text: "Ayala" },
  { value: "Baliwasan", text: "Baliwasan" },
  { value: "Baluno", text: "Baluno" },
  { value: "Barangay Zone I (Pob.)", text: "Barangay Zone I (Pob.)" },
  { value: "Barangay Zone II (Pob.)", text: "Barangay Zone II (Pob.))" },
  { value: "Barangay Zone III (Pob.)", text: "Barangay Zone III (Pob.))" },
  { value: "Barangay Zone IV (Pob.)", text: "Barangay Zone IV (Pob.)" },
  { value: "Boalan", text: "Boalan" },
  { value: "Bolong", text: "Bolong" },
  { value: "Buenavista", text: "Buenavista" },
  { value: "Bunguiao", text: "Bunguiao" },
  { value: "Busay (Sacol Island)", text: "Busay (Sacol Island)" },
  { value: "Cabaluay", text: "Cabaluay" },
  { value: "Cabatangan", text: "Cabatangan" },
  { value: "Cacao", text: "Cacao" },
  { value: "Calabasa", text: "Calabasa" },
  { value: "Camino Nuevo", text: "Camino Nuevo" },
  { value: "Campo Islam", text: "Campo Islam" },
  { value: "Canelar", text: "Canelar" },
  { value: "Capisan", text: "Capisan" },
  { value: "Cawit", text: "Cawit" },
  { value: "Culianan", text: "Culianan" },
  { value: "Dita", text: "Dita" },
  { value: "Divisoria", text: "Divisoria" },
  { value: "Dulian (Upper Bunguiao)", text: "Dulian (Upper Bunguiao)" },
  { value: "Dulian (Upper Pasonanca)", text: "Dulian (Upper Pasonanca)" },
  { value: "Guisao", text: "Guisao" },
  { value: "Guiwan", text: "Guiwan" },
  { value: "Kasanyangan", text: "Kasanyangan" },
  { value: "La Paz", text: "La Paz" },
  { value: "Lamisahan", text: "Lamisahan" },
  { value: "Landang Gua", text: "Landang Gua" },
  { value: "Landang Laum", text: "Landang Laum" },
  { value: "Lapakan", text: "Lapakan" },
  { value: "Latuan (Curuan)", text: "Latuan (Curuan)" },
  { value: "Licomo", text: "Licomo" },
  { value: "Limaong", text: "Limaong" },
  { value: "Limpapa", text: "Limpapa" },
  { value: "Lubigan", text: "Lubigan " },
  { value: "Lumayang", text: "Lumayang " },
  { value: "Lumbangan", text: "Lumbangan" },
  { value: "Lunzuran", text: "Lunzuran" },
  { value: "Maasin", text: "Maasin" },
  { value: "Malagutay", text: "Malagutay" },
  { value: "Mampang", text: "Mampang" },
  { value: "Manalipa", text: "Manalipa" },
  { value: "Mangusu", text: "Mangusu" },
  { value: "Manicahan", text: "Manicahan" },
  { value: "Mariki", text: "Mariki" },
  { value: "Mercedes", text: "Mercedes" },
  { value: "Muti", text: "Muti" },
  { value: "Pamucutan", text: "Pamucutan" },
  { value: "Pangapuyan", text: "Pangapuyan" },
  { value: "Panubigan", text: "Panubigan" },
  { value: "Pasilmanta (Sacol Island)", text: "Pasilmanta (Sacol Island)" },
  { value: "Pasobolong", text: "Pasobolong" },
  { value: "Pasonanca", text: "Pasonanca" },
  { value: "Patalon", text: "Patalon" },
  { value: "Putik", text: "Putik" },
  { value: "Quiniput", text: " Quiniput " },
  { value: "Recodo", text: "Recodo" },
  { value: "Rio Hondo", text: "Rio Hondo" },
  { value: "Salaan", text: "Salaan" },
  { value: "San Jose Cawa-Cawa", text: "San Jose Cawa-Cawa" },
  { value: "San Jose Gusu", text: "San Jose Gusu" },
  { value: "San Roque", text: "San Roque" },
  { value: "Sangali", text: "Sangali" },
  { value: "Santa Barbara", text: "Santa Barbara" },
  { value: "Santa Catalina", text: "Santa Catalina " },
  { value: "Santa Maria", text: "Santa Maria" },
  { value: "Santo Nino", text: "Santa Nino" },
  { value: "Sibulao (Caruan)", text: "Sibulao (Caruan)" },
  { value: "Sinubung", text: "Sinubung" },
  { value: "Sinunuc", text: "Sinunuc" },
  { value: "Tagasilay", text: "Tagasilay" },
  { value: "Taguiti", text: "Taguiti" },
  { value: "Talabaan", text: "Talabaan" },
  { value: "Talisayan", text: "Talisayan" },
  { value: "Talon-Talon", text: "Talon-Talon" },
  { value: "Taluksangay", text: "Taluksangay" },
  { value: "Tetuan", text: "Tetuan" },
  { value: "Tictapul", text: "Tictapul" },
  { value: "Tigbalabag", text: "Tigbalabag" },
  { value: "Tigtabon", text: "Tigtabon" },
  { value: "Tolosa", text: "Tolosa" },
  { value: "Tugbungan", text: "Tugbungan" },
  { value: "Tulungatung", text: "Tulungatung" },
  { value: "Tumaga", text: "Tumaga" },
  { value: "Tumalutab", text: "Tumalutab" },
  { value: "Tumitus", text: "Tumitus" },
  { value: "Victoria", text: "Victoria" },
  { value: "Vitali", text: "Vitali" },
  { value: "Zambowood", text: "Zambowood" },
];
