const productTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  GET_PRODUCTS: "GET_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCTS: "DELETE_PRODUCTS",
  //not sure
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  SET_STATE_PRODUCTS: " SET_STATE_PRODUCTS",
};

export default productTypes;
