const UserTypes = {
   EMAIL_SIGN_IN_START: ' EMAIL_SIGN_IN_START',
   SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
   USER_AUTH_SESSION: ' USER_AUTH_SESSION',
   SIGN_OUT_USER_START: ' SIGN_OUT_USER_START',
   SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
   SIGN_UP_USER_START: ' SIGN_UP_USER_START',
   RESET_PASS_START: 'RESET_PASS_STAR',
   RESET_PASS_SUCCESS: 'RESET_PASS_SUCCESS',
   GOOGLE_SIGN_IN_START: ' GOOGLE_SIGN_IN_START:',
   FACEBOOK_SIGN_IN_START: 'FACEBOOK_SIGN_IN_START',
   ERROR_USER: ' ERROR_USER',
   RESET_STATE_USER: 'RESET_STATE_USER'
};
 
export default UserTypes;