const UserTypes = {
  LOGIN_WITH_EMAIL: " LOGIN_WITH_EMAIL",
  PROCESSED_LOGIN: " PROCESSED_LOGIN",
  AUTHENTICATE_USER: " AUTHENTICATE_USER",
  LOGOUT_USER: " LOGOUT_USER",
  PROCESSED_LOGOUT: "PROCESSED_LOGOUT",
  USER_REGISTRY: " USER_REGISTRY",
  PASSWORD_RESET: "PASSWORD_RESET",
  PROCESSED_PASSWORD_RESET: "PROCESSED_PASSWORD_RESET",
  LOGIN_WITH_GOOGLE: " LOGIN_WITH_GOOGLE:",
  USER_ERROR: " USER_ERROR",
  STATE_OF_USER_RESET: "STATE_OF_USER_RESET",
};

export default UserTypes;
